### ISSUE TITLE
New node set_variable

### ISSUE THREAD

**Issue by jzapataikono** [iKonoTelecomunicaciones/menuflow#71]
```yaml
  - id: save_variable
    type: set_variable
    variables:
      set:
        new_variable: "Esteban"
        hard_validation: >
            {%- set random_dates = [] -%}
            {%- for n in range(5) %}
                {%- set month = range(10, 12)|random %}
                {%- set day = range(1, 30)|random %}
                {%- set year = range(2023, 2024)|random %}
                {%- set hour = range(0, 23)|random %}
                {%- set minute = range(0, 59)|random %}
                {%- set random_date = day ~ '/' ~ month ~ '/' ~ year ~ ' ' ~ hour ~ ':' ~ minute %}
                {%- set _ = random_dates.append(random_date) %}
            {%- endfor -%}
            {{ random_dates }}
      unset:
        - variable_to_unset1
        - variable_to_unset2
        - variable_to_unset3
    o_connection: "next_node"
```
